=== OscarRenilla/Proyecto_Intermodular_DAM1/Frontend/data/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="relojes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reloj" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="texto" type="xs:string"/>
                            <xs:element name="imagen" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OscarRenilla/Proyecto_Intermodular_DAM1/Frontend/data/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<relojes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="data.xsd">

    <reloj>
        <nombre>Rolex Daydate Rose Gold 40mm Ombre Black 228235 Oro rosa Negro 40mm 2025</nombre>
        <texto>El Rolex Day-Date 40 ref. 228235 en oro rosa con esfera ombré negra es la combinación perfecta de lujo y elegancia. Su exclusivo acabado en oro Everose de 18k y su distintiva esfera degradada lo convierten en una pieza sofisticada y muy deseada.</texto>
        <imagen>img/rolex-day-date.png</imagen>
    </reloj>

    <reloj>
        <nombre>Patek Philippe Nautilus</nombre>
        <texto>El Patek Philippe Nautilus 5711 es uno de los relojes más icónicos y codiciados del mundo. Su diseño elegante con carácter deportivo, junto a su inconfundible esfera y acabados de alta relojería, lo convierten en una pieza única.</texto>
        <imagen>img/nautilus.png</imagen>
    </reloj>

    <reloj>
        <nombre>Omega Speedmaster Moonwatch</nombre>
        <texto>El Omega Speedmaster Moonwatch Moonphase Co‑Axial Master Chronometer 44.25 mm Platinum es una obra maestra de la relojería, que combina innovación y tradición en un diseño imponente. Su caja de platino, esfera de oro y complicación de fase lunar elevan este modelo a otro nivel de exclusividad. Un reloj sofisticado, preciso y con una presencia inigualable.</texto>
        <imagen>img/omega-speedmaster.png</imagen>
    </reloj>

    <reloj>
        <nombre>Rolex GMT Master II</nombre>
        <texto>El Rolex GMT-Master II es un reloj de lujo diseñado para viajeros y profesionales que necesitan seguir múltiples zonas horarias. Con su icónica función GMT, su robusta construcción y su diseño atemporal, este reloj se ha convertido en un símbolo de prestigio y funcionalidad en el mundo de la relojería.</texto>
        <imagen>img/Rolex-GMT.png</imagen>
    </reloj>

    <reloj>
        <nombre>Hublot Big Bang Unico Dark Green Ceramic</nombre>
        <texto>El Hublot Big Bang Unico Dark Green Ceramic es un reloj de lujo que destaca por su diseño audaz y su innovación técnica. Con su caja de cerámica, movimiento Unico de manufactura propia y su estética vanguardista, este reloj se ha convertido en un símbolo de exclusividad y estilo en el mundo de la alta relojería.</texto>
        <imagen>img/hublot.png</imagen>
    </reloj>

    <reloj>
        <nombre>Jacob and Co. Astronomia Casino Roulette Tourbillon</nombre>
        <texto>El Jacob and Co. Astronomia Casino Roulette Tourbillon es pura extravagancia y alta relojería llevadas al extremo. Su diseño tridimensional con ruleta funcional y tourbillon lo convierte en una pieza única que no pasa desapercibida. Un reloj exclusivo para quienes buscan lujo, innovación y espectáculo en la muñeca.</texto>
        <imagen>img/jacobco.png</imagen>
    </reloj>

    <reloj>
        <nombre>Richard Mille RM 30-01</nombre>
        <texto>El Richard Mille RM 30-01 es un reloj de alta relojería diseñado para resistir las condiciones extremas del tenis profesional. Con su caja de titanio y carbono, su movimiento tourbillon y su diseño vanguardista, este reloj es una obra maestra de la ingeniería y la innovación, que combina resistencia, precisión y estilo en una pieza única.</texto>
        <imagen>img/richard-mille.png</imagen>
    </reloj>

    <reloj>
        <nombre>Tissot PRX</nombre>
        <texto>El Tissot PRX es un reloj de lujo que combina estilo y funcionalidad en un diseño atemporal. Con su caja de acero inoxidable, esfera con indicadores de hora y minutero, y su movimiento automático, este reloj es una elección perfecta para quienes buscan calidad y durabilidad en su accesorio.</texto>
        <imagen>img/reloj1.jpg</imagen>
    </reloj>

</relojes>
